export default [
  { id: 1, name: "Haberler", url: "" },
  { id: 2, name: "Dünyada Bugün", url: "dunya-basininda-bugun" },
  { id: 3, name: "Gündem", url: "gundem" },
  { id: 4, name: "Politika", url: "politika" },
  { id: 5, name: "Ekonomi", url: "ekonomi" },
  { id: 6, name: "Spor", url: "spor" },
  { id: 7, name: "Eğitim", url: "egitim" },
  { id: 8, name: "Kültür-Sanat", url: "kultur-sanat" },
  { id: 9, name: "Magazin", url: "magazin" },
  { id: 10, name: "Dünya", url: "dunya" },
  { id: 11, name: "Bilim / Teknoloji", url: "bilim-teknoloji" },
  { id: 12, name: "Çevre", url: "cevre" },
  { id: 13, name: "Sağlık", url: "saglik" },
  { id: 14, name: "Yaşam", url: "yasam" },
  { id: 15, name: "Söyleşi", url: "soylesi" },
  { id: 16, name: "Özel Dosya", url: "ozel-dosya" },
  { id: 17, name: "Videolar", url: "video" },
  { id: 18, name: "Galeri", url: "foto-haber" },
  { id: 19, name: "Haftalık", url: "haftalik" },
  { id: 20, name: "Yazarlar", url: "yazarlar" },
];
